/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "IP": {                                          "en": "ip adress of homepilot station",                  "de": "IP Adresse der Homepilot Basisstation",           "ru": "IP-адрес домашней контрольной станции",           "pt": "endereço ip da estação piloto de origem",         "nl": "IP-adres van thuis-loodsstation",                 "fr": "adresse IP de la station de pilotage à domicile", "it": "indirizzo IP della stazione pilota di casa",      "es": "dirección IP de la estación piloto",              "pl": "adres ip stacji pilota domowego"},
    "Port": {                                        "en": "Port number",                                     "de": "Port Nummer",                                     "ru": "Номер порта",                                     "pt": "Número da porta",                                 "nl": "Poortnummer",                                     "fr": "Numéro de port",                                  "it": "Numero di porta",                                 "es": "Número de puerto",                                "pl": "Numer portu"},
    "default is 12": {                               "en": "if left empty '12' will be used",                 "de": "ohne Eingabe wird '12' verwendet",                "ru": "если останется пустой «12»",                      "pt": "se deixado vazio '12' será usado",                "nl": "als dit wordt gelaten, wordt de lege '12' gebruikt", "fr": "si laissé vide '12' sera utilisé",                "it": "se lasciato vuoto verrà usato '12'",              "es": "si se deja en blanco, se usará \"12\"",           "pl": "jeśli pozostawisz puste \"12\" zostanie użyte"},
    "homepilot Adapter settings": {                  "en": "homepilot blinds Adapter settings",               "de": "Homepilot Rollladen Adapter Einstellungen",       "ru": "Настройки жалюзи homepilot",                      "pt": "configurações de adaptador de persianas do homepilot", "nl": "Homepilot blinds Adapterinstellingen",            "fr": "stores homepilot Paramètres de l'adaptateur",     "it": "homepilot blinds Impostazioni dell'adattatore",   "es": "Persianas de homepilot Configuración del adaptador", "pl": "rolety Homepilota Ustawienia adaptera"},
    "homepilot station": {                           "en": "Homepilot station",                               "de": "Homepilot Basisstation",                          "ru": "Станция Homepilot",                               "pt": "Estação de Homepilot",                            "nl": "Homepilot-station",                               "fr": "Station homepilot",                               "it": "Stazione di Homepilot",                           "es": "Estación de Homepilot",                           "pl": "Stacja Homepilot"},
    "if left empty 'homepilot.local' will be used": {"en": "if left empty 'homepilot.local' will be used",    "de": "ohne Eingabe wird 'homepilot.local' verwendet",   "ru": "если останется пустой «homepilot.local», будет использоваться", "pt": "se deixado vazio, 'homepilot.local' será usado",  "nl": "indien leeg wordt 'homepilot.local' gebruikt",    "fr": "si laissé vide 'homepilot.local' sera utilisé",   "it": "se lasciato vuoto verrà usato 'homepilot.local'", "es": "si se deja en blanco, se usará 'homepilot.local'", "pl": "jeśli zostanie użyty pusty \"homepilot.local\""},
    "normally no port setting is required": {        "en": "normally no port is required",                    "de": "normalerweise wird keine Porteingabe benötigt",   "ru": "обычно не требуется порт",                        "pt": "normalmente nenhuma porta é necessária",          "nl": "normaal is geen poort vereist",                   "fr": "Normalement, aucun port n'est requis",            "it": "normalmente non è richiesta alcuna porta",        "es": "normalmente no se requiere puerto",               "pl": "zwykle żaden port nie jest wymagany"},
};